version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template:ro
    environment:
      - BACKEND_SERVER1=${BACKEND_SERVER1}
      - BACKEND_SERVER2=${BACKEND_SERVER2}
      - BACKEND_SERVER3=${BACKEND_SERVER3}
    command: >
      /bin/bash -c "
      envsubst '$${BACKEND_SERVER1} $${BACKEND_SERVER2} $${BACKEND_SERVER3}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf &&
      nginx -g 'daemon off;'
      "
